- hosts: all
  tasks:
   - name: stop container
     shell: docker container stop mydockercontainer
   - name: remove container
     shell: docker container rm mydockercontainer
   - name: remove docker image
     shell: docker image rmi mahesh8887/docker_image
   - name: create new container
     shell: docker container run -itd --name mydockercontainer -p 8000:80 mahesh8887/docker_image
