apiVersion: apps/v1

kind: Deployment

metadata:

  labels:

    app: todo-app
    
  namespace: django-todo-app

spec:

  replicas: 1

  selector:

    matchLabels:

      app: todo-app

  template:

    metadata:

      labels:

        app: todo-app

    spec:

      containers:

      - name: todo-app

        image: mahesh8887/website:latest

        ports:

        - containerPort: 80
